services:
  attestation-agent:
    build:
      dockerfile: Dockerfile.aa
    environment:
      - RUST_LOG=debug
      - TRUSTEE_ADDR=${TRUSTEE_ADDR}
      - AS_ADDR=${TRUSTEE_ADDR}/as/
    volumes:
      - attestation-agent-sock:/run/confidential-containers/attestation-agent/
    devices:
      - /dev/tdx_guest
    privileged: true
    cap_add:
      - NET_ADMIN
    network_mode: host
    init: true
    command: [ "sh", "-c", "start.sh --trustee-addr ${TRUSTEE_ADDR} --as-addr ${TRUSTEE_ADDR}/as/" ]
    healthcheck:
      test: [ "CMD-SHELL", "ss -n --listen | grep /run/confidential-containers/attestation-agent/attestation-agent.sock" ]
      interval: 3s
      start_period: 0s
      start_interval: 3s
      retries: 5
      timeout: 5s

  confidential-data-hub:
    build:
      dockerfile: Dockerfile.cdh
    environment:
      - TRUSTEE_ADDR=${TRUSTEE_ADDR}
      - CDH_KEY_ID=kbs:///${KBS_KEY_PATH}
    volumes:
      - attestation-agent-sock:/run/confidential-containers/attestation-agent/
      - decryption-key:/tmp/gocryptfs-decryptionkey
    network_mode: host
    init: true
    command:
      - start.sh
      - --trustee-addr
      - ${TRUSTEE_ADDR}
      - --key-id
      - ${CDH_KEY_ID}
      - --resource-path
      - /tmp/gocryptfs-decryptionkey/key
    healthcheck:
      test: [ "CMD-SHELL", "[ -f /tmp/gocryptfs-decryptionkey/key ]" ]
      interval: 10s
      start_period: 0s
      start_interval: 3s
      retries: 5
      timeout: 5s
    depends_on:
      attestation-agent:
        condition: service_healthy

  gocryptfs:
    build:
      dockerfile: Dockerfile.gocryptfs
    environment:
      - BUCKET_NAME=${BUCKET_NAME}
      - MODEL_TYPE=${MODEL_TYPE}
      - ACCESS_KEY=${ACCESS_KEY}
      - ACCESS_SECRET=${ACCESS_SECRET}
    volumes:
      - /tmp/encrypted-model:/tmp/encrypted-model:shared
      - /tmp/plaintext-model:/tmp/plaintext-model:shared
      - decryption-key:/tmp/gocryptfs-decryptionkey
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    network_mode: host
    init: true
    command:
      - start.sh
    healthcheck:
      test: [ "CMD-SHELL", "mount | grep /tmp/plaintext-model" ]
      interval: 10s
      start_period: 0s
      start_interval: 3s
      retries: 5
      timeout: 5s
    depends_on:
      confidential-data-hub:
        condition: service_healthy
        restart: true
      # tng:
      #   condition: service_healthy
      #   restart: false

volumes:
  attestation-agent-sock:
  decryption-key:
